### ISSUE TITLE
Speeding up model creation

### ISSUE THREAD

**Issue by lnksz** [tum-ens/rivus#26]
As the [`create_model`](https://github.com/tum-ens/rivus/blob/af4df6bf93325ba5952866933a7e560de168b5ed/rivus/main/rivus.py#L101) function is quite slow (10s< even for small models). The time it takes is often comparable or even longer than the time, the actual solving needs.
I profiled the code with [line_profiler](http://mortada.net/easily-profile-python-code-in-jupyter.html) and the hot spots are clearly the `pyomo.Constrain` generations.

| Percent of execution time spent in the line  | Assignment in the line                                 |
| -------------------------------------------- | ------------------------------------------------------ |
| 18.0                                         | m.vertex_equation = pyomo.Constraint(...)              |
| 17.5                                         | m.process_output = pyomo.Constraint(...)               |
| 14.9                                         | m.hub_supply = pyomo.Constraint(...)                   |
| 11.6                                         | m.peak_satisfaction = pyomo.Constraint(...)            |
| 10.8                                         | m.edge_equation = pyomo.Constraint(...)                |
| 8.5                                          | m.process_input = pyomo.Constraint(...)                |
| 8.1                                          | m.def_costs = pyomo.Constraint(...)                    |
| 5.6                                          | m.commodity_maximum = pyomo.Constraint(...)            |
| 2.2                                          | m.arc_flow_unidirectionality = pyomo.Constraint(...)   |
| 0.3                                          | m.arc_flow_by_capacity = pyomo.Constraint(...)         |

That makes a sum of ca. 97.5 %.
It would be a nice investigation, to see whether one could chop this time down. (Mainly in the top 5 calls)

**Comment by ojdo** [comment]
Given the observation made by @tzipperle [on a similar case in urbs](https://github.com/tum-ens/urbs/pull/140), I fear the culprit here is the same as there: the calls to Pandas' `.loc` function for convenient, label-based access to DataFrame elements. I always had assumed this to be a cheap operation. But unfortunately, it is more geared towards few, "fat" calls.

His solution there: convert the relevant DataFrame column to a plain `dict`, which is designed for fast, key-based access to single elements.

**Comment by lnksz** [comment]
Hah! This happened a week ago? Now I added urbs to my watched repos!
Now I am happy I added this issue before investing more time into this topic! :relaxed: 
Thank you for the link.

**Comment by lnksz** [comment]
After changing the same m.r_in variable, the positive effect is certain.

| Original | with r_xx_dict  | Assignment in the line                                 |
| -------- | --------------- | ------------------------------------------------------ |
| **18.0**     | **1.1**             | m.vertex_equation = pyomo.Constraint(...)              |
| 17.5     | 22.2            | m.process_output = pyomo.Constraint(...)               |
| 14.9     | 18.9            | m.hub_supply = pyomo.Constraint(...)                   |
| 11.6     | 14.4            | m.peak_satisfaction = pyomo.Constraint(...)            |
| 10.8     | 13.5            | m.edge_equation = pyomo.Constraint(...)                |
| 8.5      | 10.1            | m.process_input = pyomo.Constraint(...)                |
| 8.1      | 10.0            | m.def_costs = pyomo.Constraint(...)                    |
| **5.6**      | **3.7**             | m.commodity_maximum = pyomo.Constraint(...)            |
| 2.2      | 2.3             | m.arc_flow_unidirectionality = pyomo.Constraint(...)   |
| 0.3      | 0.7             | m.arc_flow_by_capacity = pyomo.Constraint(...)         |

~~In particular (with line_profiler) this meant a reduction of model creation by 5s (22->17) which is about 23% performance gain.~~

~~All the gain comes from the speed-up of `m.vertex_equation` and `m.commodity_maximum` and as such,~~ there is still ~~a decent amount of hidden~~ some perspective, as `loc` is used extensively in the defining rules.
**----- EDIT -----**
I found a copy-paste error in my edit (a fantastically named variable `h` was left as `p`...) in the `hub_balance` function.
After that, the results look much like expected.
New execution time is around 6-7s. That is ca. 68% gain. That is nice.  (22s -> 6-7s )
**----- EDIT 2 -----**
I explored the rest of the opportunities, what the dict conversion offers. The results are shown below, each row introducing extra substitution in addition to the earlier rows' actions.

| to dict     | CumSum [s]         | relative boost [%] |
| --------    | ----------       | ---------------- |
| original    | 22.1             | 0              |
| r_in, r_out | 6-7              | 68               |
| edge.geo    | 4-5              | 77               |
| peak        | 3-4              | 84               |
| commodity   | 2-3              | 88               |
| process     | ~2               | 90               |
| time        | <2               | 92               |
| hub         | ~1.6             | 93               |

**Comment by ojdo** [comment]
I see two options on how to proceed:

  - Either change the way *all* input data is treated within create_model, or
  - Try out using .at instead of .loc. [pandas doc](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.at.html). With a little luck, this method might already reach speed close to native dict lookup.

Creating a minimal test-case comparison using one DataFrame from ˋmimo-example.xlsxˋ might yield enlightening results.

**Comment by lnksz** [comment]
I will have a look at the `loc, at, and get_value` variations as [this](https://stackoverflow.com/a/37216587/6232305) answer suggests.
I noticed, that m.process_output did not experience any speed-up, although from its rule I would have awaited that.
``` python
def process_output_rule(m, v, p, co, t):
    # return m.Epsilon_out[v, p, co, t] == m.Tau[v, p, t] * m.r_out.loc[p, co]
    return m.Epsilon_out[v, p, co, t] == m.Tau[v, p, t] * m.r_out_dict[(p, co)]
```

> Creating a minimal test-case comparison using one DataFrame from ˋmimo-example.xlsxˋ might yield enlightening results.

Isn't mimo an urbs example?

**Comment by lnksz** [comment]
I will have a look at the `loc, at, and get_value` variations as [this](https://stackoverflow.com/a/37216587/6232305) answer suggests.

After some headache caused by the fact, that `r_in` and `m.r_out` are not DataFrames but Series. (And as such `at, get_value`  of course will not work as expected...
The following profiling shows, that (up till now) `at, get_value` do not show too promising speed-ups.
(Anyway, if only one value is looked up, they are still faster and label based)

``` python
>>> import timeit as tit
>>> dfout = m.r_out.to_frame()
>>> m.r_out.loc['Gas power plant', 'CO2']
0.02
>>> dfout.loc['Gas power plant', 'CO2']['ratio']
0.02
>>> dfout.at[('Gas power plant', 'CO2'), 'ratio']
0.02
>>> dfout.get_value(('Gas power plant', 'CO2'), 'ratio')
0.02
>>> tit.timeit("m.r_out.loc['Gas power plant', 'CO2']", number=10000, globals=dict(m=m))
21.440592079874477
>>> tit.timeit("dfout.loc['Gas power plant', 'CO2']['ratio']", number=10000, globals=dict(dfout=dfout))
22.88835751410204
>>> tit.timeit("dfout.at[('Gas power plant', 'CO2'), 'ratio']", number=10000, globals=dict(dfout=dfout))
20.800039411779153
>>> tit.timeit("dfout.get_value(('Gas power plant', 'CO2'), 'ratio')", number=10000, globals=dict(dfout=dfout))
20.881049383752718
>>> ddout = m.r_out.to_dict()
>>> tit.timeit("ddout[('Gas power plant', 'CO2')]", number=10000, globals=dict(ddout=ddout))
0.0014019919370866774
```
The last row shows why a dict look-up can mean such a boost

**Comment by lnksz** [comment]
For regex code substitution (tested in Sublime 3) I use:
`m\.params\['hub'\]\.loc\[(.+?)\]\[(.+?)\]`
to find parts like this: `m.params['hub'].loc[index][col]`
which can be replaced by `m.hub_dict[(col, index)]`
through `m.hub_dict[$2][$1]`

You can get the idea and modify for multi-index or other parameter names.

I also added a [PR](https://github.com/tum-ens/rivus/pull/27) with the above-described changes.

I think even if all `.loc` to `dict` is merged, it is a manageable workaround from code maintenance's perspective.
(Acceptable memory trade-off, plus reserving the cool DataFrame features at the data preparation.)
