### ISSUE TITLE
Writethedocs setup

### ISSUE THREAD

**Issue by lnksz** [tum-ens/rivus#41]
Hey, @ojdo set up the readthedocs rivus site so that it is built from his own fork. See [project overview](http://readthedocs.org/projects/rivus/) in the upper right corner.

Like this the rivus.readthedocs.io domain is taken. @ojdo  please modify the path in the readthedocs admin side.

**Comment by ojdo** [comment]
Ouch, thanks for the hint. The path is fixed, the docs should now be based on this repository. (I had to Ctrl-Refresh my browser in order to prevent local caching.)

Please verify yourself and close if pleased with the result :-)

**Comment by lnksz** [comment]
Thanks!
